# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/athar/OneDrive/Documents/GitHub/lab-4-AtharvaPan265/Lab_4/Lab_4.srcs/sources_1/ip/picture/picture.xci
# IP: The module: 'picture' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/athar/OneDrive/Documents/GitHub/lab-4-AtharvaPan265/Lab_4/Lab_4.gen/sources_1/ip/picture/picture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/athar/OneDrive/Documents/GitHub/lab-4-AtharvaPan265/Lab_4/Lab_4.srcs/sources_1/ip/picture/picture.xci
# IP: The module: 'picture' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/athar/OneDrive/Documents/GitHub/lab-4-AtharvaPan265/Lab_4/Lab_4.gen/sources_1/ip/picture/picture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
